# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: manipulator
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6

  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
manipulator_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10

controller_list:
    - name: "manipulator_controller"
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      joints:
        - joint1
        - joint2
        - joint3
        - joint4
        - joint5
        - joint6